directories:
  root: ./vanguard-ab-test/
  data: ./vanguard-ab-test/data/
    clean: ./vanguard-ab-test/data/clean/
    raw: ./vanguard-ab-test/data/raw/
    sql: ./vanguard-ab-test/data/sql/
      Age_Analysis: ./vanguard-ab-test/data/sql/Age_Analysis/
      Tenure_Analysis: ./vanguard-ab-test/data/sql/Tenure_Analysis/
  notebook: ./vanguard-ab-test/notebook/
  presentation: ./vanguard-ab-test/presentation/
    Tableau: ./vanguard-ab-test/presentation/tableau/
  resources: ./vanguard-ab-test/resources/
    img: ./vanguard-ab-test/resources/img/
  src: ./vanguard-ab-test/src/
    functions: ./vanguard-ab-test/src/functions/

data_paths:
  demo: '../data/raw/df_final_demo.txt'
  experiment: '../data/raw/df_final_experiment_clients.txt'
  web_data_1: '../data/raw/df_final_web_data_pt_1.txt'
  web_data_2: '../data/raw/df_final_web_data_pt_2.txt'
  clean_demo: '../data/clean/clean_df_demo.csv'
  clean_experiment: '../data/clean/clean_df_experiment_clients.csv'
  clean_web_data_1: '../data/clean/clean_df_web_data_pt_1.csv'
  clean_web_data_2: '../data/clean/clean_df_web_data_pt_2.csv'
